# Generated by Django 6.0.2 on 2026-02-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTokenSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colors', models.JSONField(blank=True, default=dict, help_text='Brand and surface colors: {terracotta, teal, gold, green, parchment, darkGround, cream}')),
                ('fonts', models.JSONField(blank=True, default=dict, help_text='Font mappings: {title, body, mono, annotation, tagline}')),
                ('spacing', models.JSONField(blank=True, default=dict, help_text='Spacing values: {contentMaxWidth, heroMaxWidth}')),
                ('section_colors', models.JSONField(blank=True, default=dict, help_text='Which brand color maps to which section')),
            ],
            options={
                'verbose_name': 'Design tokens',
                'verbose_name_plural': 'Design tokens',
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, default='', help_text='SketchIcon name (e.g. file-text, note-pencil)', max_length=50)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_key', models.CharField(choices=[('home', 'Homepage'), ('essays', 'Essays listing'), ('essay_detail', 'Essay detail'), ('field_notes', 'Field Notes listing'), ('field_note_detail', 'Field Note detail'), ('projects', 'Projects'), ('shelf', 'Shelf'), ('toolkit', 'Toolkit'), ('connect', 'Connect'), ('colophon', 'Colophon'), ('now', 'Now')], max_length=50, unique=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Page-specific component configuration')),
            ],
            options={
                'ordering': ['page_key'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('footer_tagline', models.CharField(blank=True, default='', max_length=500)),
                ('footer_links', models.JSONField(blank=True, default=list, help_text='Array of {label, url} objects')),
                ('seo_title_template', models.CharField(blank=True, default='%s | travisgilbert.com', max_length=200)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('seo_og_image_fallback', models.CharField(blank=True, default='', max_length=500)),
                ('global_toggles', models.JSONField(blank=True, default=dict, help_text='Feature flags: {dotgrid_enabled, paper_grain_enabled, console_easter_egg}')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='ToolkitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('category', models.CharField(blank=True, default='', help_text='Toolkit category (e.g. production, research, automation)', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('body', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('composition', models.JSONField(blank=True, default=dict, help_text='Per-instance visual overrides')),
            ],
            options={
                'verbose_name_plural': 'toolkit entries',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='essay',
            name='composition',
            field=models.JSONField(blank=True, default=dict, help_text='Per-instance visual overrides (heroStyle, overlay, accent)'),
        ),
        migrations.AddField(
            model_name='fieldnote',
            name='composition',
            field=models.JSONField(blank=True, default=dict, help_text='Per-instance visual overrides'),
        ),
        migrations.AddField(
            model_name='project',
            name='composition',
            field=models.JSONField(blank=True, default=dict, help_text='Per-instance visual overrides (tint override, etc.)'),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='shelfentry',
            name='composition',
            field=models.JSONField(blank=True, default=dict, help_text='Per-instance visual overrides'),
        ),
        migrations.AddField(
            model_name='shelfentry',
            name='stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='publishlog',
            name='content_type',
            field=models.CharField(choices=[('essay', 'Essay'), ('field_note', 'Field Note'), ('shelf', 'Shelf Entry'), ('project', 'Project'), ('toolkit', 'Toolkit Entry'), ('now', 'Now Page'), ('site_config', 'Site Config')], max_length=20),
        ),
    ]
