# Generated by Django 6.0.2 on 2026-02-27 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawsource',
            name='connections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rawsource',
            name='importance',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6),
        ),
        migrations.AddField(
            model_name='rawsource',
            name='input_type',
            field=models.CharField(choices=[('url', 'URL'), ('file', 'File')], default='url', max_length=4),
        ),
        migrations.AddField(
            model_name='rawsource',
            name='phase',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('review', 'Review'), ('decided', 'Decided')], default='inbox', max_length=7),
        ),
        migrations.AddField(
            model_name='rawsource',
            name='scrape_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=8),
        ),
        migrations.AddField(
            model_name='rawsource',
            name='source_file',
            field=models.FileField(blank=True, upload_to='sourcebox/'),
        ),
        migrations.AlterField(
            model_name='rawsource',
            name='url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='suggestedconnection',
            name='raw_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_connections', to='intake.rawsource'),
        ),
    ]
