# Generated by Django 6.0.2 on 2026-02-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_rawsource_connections_rawsource_importance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuggestedConnection',
        ),
    ]
