# Generated by Django 6.0.2 on 2026-02-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_type', models.CharField(choices=[('sources', 'Sources'), ('links', 'Source Links'), ('threads', 'Threads'), ('mentions', 'Mentions'), ('full', 'Full Publish')], db_index=True, max_length=20)),
                ('record_count', models.PositiveIntegerField(default=0, help_text='Number of records included in this publish.')),
                ('commit_sha', models.CharField(blank=True, help_text='Git commit SHA from the GitHub API.', max_length=40)),
                ('commit_url', models.URLField(blank=True, help_text='URL to the commit on GitHub.', max_length=2000)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('error_message', models.TextField(blank=True, help_text='Error details if the publish failed.')),
            ],
            options={
                'verbose_name': 'publish log',
                'verbose_name_plural': 'publish logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['success', '-created_at'], name='idx_publog_success_date')],
            },
        ),
    ]
