# Generated by Django 6.0.2 on 2026-02-26 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this research thread is investigating.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=20)),
                ('started_date', models.DateField(blank=True, help_text='When this line of investigation began.', null=True)),
                ('completed_date', models.DateField(blank=True, help_text='When the investigation concluded.', null=True)),
                ('resulting_essay_slug', models.SlugField(blank=True, help_text='Slug of the essay this thread produced (if any).', max_length=300)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('public', models.BooleanField(db_index=True, default=True, help_text='Whether this thread appears on the public site.')),
            ],
            options={
                'ordering': ['-started_date', '-created_at'],
                'indexes': [models.Index(fields=['public', '-started_date'], name='idx_thread_public_date')],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('creator', models.CharField(blank=True, help_text='Author, director, or primary creator.', max_length=500)),
                ('source_type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('paper', 'Academic Paper'), ('video', 'Video'), ('podcast', 'Podcast'), ('dataset', 'Dataset'), ('document', 'Document'), ('report', 'Report'), ('map', 'Map'), ('archive', 'Archive'), ('interview', 'Interview'), ('website', 'Website'), ('other', 'Other')], db_index=True, default='article', max_length=20)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('publication', models.CharField(blank=True, help_text='Publisher, journal, outlet, or platform.', max_length=300)),
                ('date_published', models.DateField(blank=True, help_text='When this source was originally published.', null=True)),
                ('date_encountered', models.DateField(blank=True, help_text='When you first encountered this source.', null=True)),
                ('private_annotation', models.TextField(blank=True, help_text='Personal notes. Not published to the site.')),
                ('public_annotation', models.TextField(blank=True, help_text='What readers see on the site.')),
                ('key_findings', models.JSONField(blank=True, default=list, help_text='Key takeaways, e.g. ["Finding one", "Finding two"].')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization, e.g. ["urban-design", "housing"].')),
                ('public', models.BooleanField(db_index=True, default=True, help_text='Whether this source appears on the public site.')),
                ('location_name', models.CharField(blank=True, help_text='Human readable location name.', max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', '-created_at'], name='idx_source_type_date'), models.Index(fields=['public', '-created_at'], name='idx_source_public_date')],
            },
        ),
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('essay', 'Essay'), ('field_note', 'Field Note')], db_index=True, max_length=20)),
                ('content_slug', models.SlugField(max_length=300)),
                ('content_title', models.CharField(blank=True, help_text='Display title (denormalized for admin convenience).', max_length=500)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('background', 'Background'), ('inspiration', 'Inspiration'), ('data', 'Data'), ('counterargument', 'Counterargument'), ('methodology', 'Methodology'), ('reference', 'Reference')], db_index=True, default='reference', help_text='How this source was used in the content.', max_length=20)),
                ('key_quote', models.TextField(blank=True, help_text='Representative quote from or about this source in context.')),
                ('date_linked', models.DateField(blank=True, help_text='When this source was connected to the content.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this link.')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='research.source')),
            ],
            options={
                'verbose_name': 'source link',
                'verbose_name_plural': 'source links',
                'ordering': ['content_type', 'content_slug'],
                'indexes': [models.Index(fields=['content_type', 'content_slug'], name='idx_link_content_lookup'), models.Index(fields=['role'], name='idx_link_role')],
                'constraints': [models.UniqueConstraint(fields=('source', 'content_type', 'content_slug'), name='unique_source_per_content')],
            },
        ),
        migrations.CreateModel(
            name='ThreadEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('source', 'Source'), ('note', 'Note'), ('milestone', 'Milestone'), ('connection', 'Connection'), ('question', 'Question')], db_index=True, default='note', max_length=20)),
                ('date', models.DateField(help_text='When this entry occurred.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the thread (lower first).')),
                ('field_note_slug', models.SlugField(blank=True, help_text='Slug of a related field note (cross-service reference).', max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, help_text='What happened or what was discovered.')),
                ('source', models.ForeignKey(blank=True, help_text='Source relevant to this entry (for "source" type entries).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_entries', to='research.source')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='research.researchthread')),
            ],
            options={
                'verbose_name_plural': 'thread entries',
                'ordering': ['order', '-date'],
                'indexes': [models.Index(fields=['thread', 'order'], name='idx_entry_thread_order')],
            },
        ),
    ]
