# Generated by Django 6.0.2 on 2026-02-26 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_content_type', models.CharField(choices=[('essay', 'Essay'), ('field_note', 'Field Note')], default='essay', max_length=20)),
                ('from_slug', models.CharField(max_length=300)),
                ('to_content_type', models.CharField(choices=[('essay', 'Essay'), ('field_note', 'Field Note')], default='essay', max_length=20)),
                ('to_slug', models.CharField(max_length=300)),
                ('explanation', models.TextField(help_text='How these pieces of content relate to each other.', max_length=1000)),
                ('contributor_name', models.CharField(max_length=100)),
                ('contributor_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_connection_status')],
                'constraints': [models.UniqueConstraint(fields=('from_slug', 'to_slug'), name='unique_connection_suggestion')],
            },
        ),
        migrations.CreateModel(
            name='SourceSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the suggested source.', max_length=500)),
                ('url', models.URLField(blank=True, help_text='Link to the source.', max_length=2000)),
                ('source_type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('paper', 'Academic Paper'), ('video', 'Video'), ('podcast', 'Podcast'), ('dataset', 'Dataset'), ('document', 'Document'), ('report', 'Report'), ('map', 'Map'), ('archive', 'Archive'), ('interview', 'Interview'), ('website', 'Website'), ('other', 'Other')], default='article', max_length=20)),
                ('relevance_note', models.TextField(help_text="Why this source is relevant (the contributor's words).", max_length=1000)),
                ('target_content_type', models.CharField(choices=[('essay', 'Essay'), ('field_note', 'Field Note')], default='essay', help_text='essay or field_note.', max_length=20)),
                ('target_slug', models.CharField(help_text='Slug of the content this source relates to.', max_length=300)),
                ('contributor_name', models.CharField(help_text='Display name of the contributor.', max_length=100)),
                ('contributor_url', models.URLField(blank=True, help_text='Optional website or social link for attribution.', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True, help_text='Internal note about why this was approved/rejected.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged as potential spam by reCAPTCHA score.')),
                ('promoted_source', models.ForeignKey(blank=True, help_text='The Source created when this suggestion was approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='research.source')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_suggestion_status_date'), models.Index(fields=['target_slug'], name='idx_suggestion_target')],
            },
        ),
    ]
